"""Phase 14 -- Diff Engine output. An AssetChangeEvent is a structured,
persisted record of one detected difference between two comparable Jobs
(same asset + tool + profile + params) for the same Asset. Generated by
app/diff/service.py, never written directly by an API route.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, String, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base
from app.models.finding import Severity


class ChangeType(str, enum.Enum):
    PORT_OPENED = "PORT_OPENED"
    PORT_CLOSED = "PORT_CLOSED"
    SERVICE_CHANGED = "SERVICE_CHANGED"
    TECHNOLOGY_ADDED = "TECHNOLOGY_ADDED"
    TECHNOLOGY_REMOVED = "TECHNOLOGY_REMOVED"
    TECHNOLOGY_CHANGED = "TECHNOLOGY_CHANGED"
    CERTIFICATE_CHANGED = "CERTIFICATE_CHANGED"
    HTTP_CHANGED = "HTTP_CHANGED"
    OTHER = "OTHER"


class AssetChangeEvent(Base):
    __tablename__ = "asset_change_events"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # CASCADE: an asset's change timeline has no meaning without the asset
    # (unlike Job, which is kept for audit trail independent of its
    # Project/Target -- see Phase 11/13). Deleting the asset deletes its
    # change history with it, documented in phase-14-continuous-recon.md.
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("assets.id", ondelete="CASCADE"), nullable=False
    )
    job_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    previous_job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="SET NULL"), nullable=True
    )

    change_type: Mapped[ChangeType] = mapped_column(Enum(ChangeType, name="asset_change_type"), nullable=False)
    severity: Mapped[Severity] = mapped_column(Enum(Severity, name="finding_severity"), nullable=False)
    # Human-readable identifier of what changed, e.g. "port:8080/tcp",
    # "technology:nginx", "certificate.subject" -- not free text, always
    # generated by app/diff/engine.py from structured comparison, never
    # copied verbatim from raw tool output without going through str().
    field: Mapped[str] = mapped_column(String(256), nullable=False)
    old_value: Mapped[str | None] = mapped_column(Text, nullable=True)
    new_value: Mapped[str | None] = mapped_column(Text, nullable=True)
    change_metadata: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)

    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))
