"""Phase 16 -- Finding lifecycle audit trail and cross-tool correlation.
Both tables are append-only / system-generated: no API route ever writes
FindingStatusHistory directly (app/findings/lifecycle.py does), and no API
route ever writes FindingRelation directly (app/findings/correlation.py
does, from a fixed set of explicit rules -- see docs/phase-16-correlation-
deduplication.md).
"""

import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, Index, String, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base
from app.models.finding import FindingStatus


class FindingStatusHistory(Base):
    __tablename__ = "finding_status_history"
    __table_args__ = (Index("ix_finding_status_history_finding_id", "finding_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    finding_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("findings.id", ondelete="CASCADE"), nullable=False
    )
    old_status: Mapped[FindingStatus | None] = mapped_column(
        Enum(FindingStatus, name="finding_status"), nullable=True
    )
    new_status: Mapped[FindingStatus] = mapped_column(Enum(FindingStatus, name="finding_status"), nullable=False)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    # "manual" (PATCH /api/findings/{id}/status, a human decision) or
    # "automatic" (re-observation reopening a REMEDIATED/FALSE_POSITIVE
    # finding) -- CyberLab is mono-user (see security.md#rbac), so this
    # distinguishes *how* a transition happened rather than *who* did it.
    triggered_by: Mapped[str] = mapped_column(String(16), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))


class FindingRelation(Base):
    __tablename__ = "finding_relations"
    __table_args__ = (
        # Canonical ordering (finding_id < related_finding_id as UUIDs,
        # enforced by app/findings/correlation.py) plus the rule that
        # created it -- prevents both (A,B) and (B,A) duplicates, and lets
        # the same two findings be linked by more than one distinct rule.
        UniqueConstraint("finding_id", "related_finding_id", "rule", name="uq_finding_relation"),
        Index("ix_finding_relations_finding_id", "finding_id"),
        Index("ix_finding_relations_related_finding_id", "related_finding_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    finding_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("findings.id", ondelete="CASCADE"), nullable=False
    )
    related_finding_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("findings.id", ondelete="CASCADE"), nullable=False
    )
    # e.g. "RULE_NMAP_WHATWEB_PORT" -- see app/findings/correlation.py for
    # the fixed set of rules. Never a free-form string from a request.
    rule: Mapped[str] = mapped_column(String(64), nullable=False)
    # Human-readable, e.g. "nmap identified port 80 as HTTP and whatweb
    # identified Apache on the same service." Always generated by the rule
    # itself, never accepted as API input.
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    relation_metadata: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))
