"""add profile column to jobs

Revision ID: 3a248ef9f137
Revises: 6495416ebbf2
Create Date: 2026-08-10 12:45:54.675408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a248ef9f137'
down_revision: Union[str, None] = '6495416ebbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('profile', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'profile')
    # ### end Alembic commands ###
