"""add ai_analysis to jobs

Revision ID: 566dc8667e8a
Revises: 0231b8dbb64b
Create Date: 2026-08-10 00:31:40.446809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '566dc8667e8a'
down_revision: Union[str, None] = '0231b8dbb64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ai_analysis')
    # ### end Alembic commands ###
