"""add projects and targets, link jobs to them

Revision ID: 6495416ebbf2
Revises: 6ad0daaf9daa
Create Date: 2026-08-10 10:47:11.146215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6495416ebbf2'
down_revision: Union[str, None] = '6ad0daaf9daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('hostname', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('target_type', sa.Enum('HOST', 'IP', 'DOMAIN', 'URL', 'CONTAINER', 'LAB', 'OTHER', name='target_type'), nullable=False),
    sa.Column('authorization_status', sa.Enum('LAB', 'AUTHORIZED', 'LOCAL', 'UNKNOWN', name='target_authorization_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('target_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'targets', ['target_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Phase 23 -- fixed: the autogenerated `op.drop_constraint(None, ...)`
    # calls below were never filled in with real constraint names (the
    # `# please adjust!` comment above was never acted on), so running this
    # downgrade would fail outright with a NULL constraint name. This ONLY
    # changes downgrade() -- upgrade() and every already-applied instance of
    # this migration are untouched; a historical migration's forward
    # behavior is never edited, only its (until now unusable) rollback path.
    # Real constraint names confirmed against a live database that had
    # already run this migration's upgrade():
    #   jobs_project_id_fkey, jobs_target_id_fkey
    op.drop_constraint('jobs_target_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_project_id_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'target_id')
    op.drop_column('jobs', 'project_id')
    op.drop_table('targets')
    op.drop_table('projects')

    # Phase 23 -- also fixed: op.drop_table() never drops the Postgres ENUM
    # TYPEs a dropped column used, only the autogenerate-created tables --
    # confirmed by actually re-running upgrade() immediately after this
    # downgrade on a live database, which failed with "type project_status
    # already exists" before this fix. checkfirst=True matches every other
    # enum-owning migration's downgrade in this chain (e.g. 392e4638a4d8,
    # d4f6b1e8c9a7). Dropped after the tables/columns that used them, since
    # Postgres refuses to drop a type still referenced by a column.
    sa.Enum(name='project_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='target_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='target_authorization_status').drop(op.get_bind(), checkfirst=True)
